import React from "react";
import { SignedOut, SignInButton, SignedIn, SignOutButton, useUser } from "@clerk/nextjs";
import { NextPage } from "next";
import Head from "next/head";

import DropDownMap from "~/components/DropDownMap";

const Header: React.FC = () => {
	return (
		<header className="w-full py-4 px-8  bg-gradient-to-b from-white to-[#3f4243] shadow-md fixed top-0 left-0 z-50">
			<div className="container mx-auto flex items-center justify-between">
				<div className="text-xl font-semibold">
				</div>
				<div>
					<SignedOut>
						<div className="bg-blue-400 border-blue-400 rounded-lg px-4 py-2">
							<SignInButton />
						</div>
					</SignedOut>
					<SignedIn>
						<div className="bg-red-400 border-red-400 px-4 py-2 rounded-lg">
							<SignOutButton />
						</div>
					</SignedIn>
				</div>
			</div>
		</header>
	);
};

const Home: NextPage = () => {
	const user = useUser();

	console.log("user", user);

	const ProtectedContent = () => (
		<>
			<p className="text-4xl mb-8">Welcome, {user.user?.externalAccounts[0]?.username}!</p>
			<DropDownMap />
		</>
	);

	return (
		<>
			<Head>
				<title>Mazer Rachkam</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#edebf5] to-[#3f4243] pt-20">
				<div>
					<SignedIn>
						<ProtectedContent />
					</SignedIn>
				</div>
			</main>
		</>
	);
};

export default Home;
