import React from "react";
import { NextPage } from "next";
import Head from "next/head";
import Header from "~/components/Header";
import DropDownMap from "~/components/DropDownMap";
import { SignedIn, SignedOut, useUser } from "@clerk/nextjs";
import { useRouter } from "next/router";
import LoginRequired from "~/components/LoginRequired";

const Home: NextPage = () => {
	const { user } = useUser();
	const router = useRouter();

	console.log("user", user);

	const ProtectedContent = () => (
		<>
			<p className="text-4xl mb-8">Welcome, {user?.firstName}!</p>
			<DropDownMap />
		</>
	);

	return (
		<>
			<Head>
				<title>Dallin Humphrey</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/pineapple.jpg" />
			</Head>
			<Header />
			<main className="flex min-h-screen flex-col items-center justify-center bg-slate-500 pt-20">
				<div className="w-1/2">
					<SignedOut>
						<LoginRequired />
					</SignedOut>
					<SignedIn>
						<ProtectedContent />
					</SignedIn>
				</div>
			</main>
		</>
	);
};

export default Home;
